apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-example-rules
  labels:
    prometheus: prometheus
    role: alert-rules
spec:
  groups:
    - name: ./example.rules
      rules:
        - alert: ExampleAlert
          expr: vector(1)
    - name: ./api.rules
      rules:
        - alert: HighErrorRate
          expr: increase(api_request_error_count[1m]) > 1
          labels:
            app: api
          annotations:
            summary: "Pod {{ $labels.pod }} throws errors"
