apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  alerting:
    alertmanagers:
      - namespace: default
        name: alertmanager-general
        port: web
  externalUrl: http://localhost:30900
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: prometheus
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      monitoring: general
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
