apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: general
  labels:
    monitoring: general
spec:
  selector:
    matchLabels:
      monitoring: general
  endpoints:
    - port: metrics
      interval: "15s"
