apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  type: ClusterIP
  ports:
    - name: opencensus
      port: 55678
      protocol: TCP
      targetPort: 55678
    - name: opentelemetry
      port: 55680
      protocol: TCP
      targetPort: 55680
    - name: zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    app.kubernetes.io/name: otel-collector
