global:
  resolve_timeout: 5m
route:
  group_by: ["job"]
  group_wait: 0s
  group_interval: 1m
  repeat_interval: 12h
  receiver: "webhook"
receivers:
  - name: "webhook"
    webhook_configs:
      - url: "http://alert-tester/hook"
