apiVersion: v1
kind: Namespace
metadata:
  name: ingress-traefik
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/trace-collector: otel-collector.otel-collector:55678
    config.alpha.linkerd.io/trace-collector-service-account: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: ingress-traefik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: ingress-traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: ingress-traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-traefik
subjects:
  - kind: ServiceAccount
    name: ingress-traefik
    namespace: ingress-traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: ingress-traefik
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: ingress-traefik
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: ingress-traefik
    spec:
      serviceAccountName: ingress-traefik
      nodeSelector:
        ingress-ready: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
      dnsPolicy: ClusterFirst
      containers:
        - image: traefik:2.2.8
          name: ingress-traefik
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
              hostPort: 80
          args:
            - --api=false
            - --api.dashboard=false
            - --entryPoints.web.address=:80
            - --ping=true
            - --providers.kubernetesingress
            - --tracing=true
            - --tracing.serviceName=ingress
            - --tracing.zipkin.httpEndpoint=http://otel-collector.otel-collector.svc.cluster.local:9411/api/v2/spans
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            allowPrivilegeEscalation: true
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: ingress-traefik
  annotations:
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: ingress-traefik
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
