apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: api
              servicePort: 80
