apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-tester
spec:
  selector:
    matchLabels:
      app: alert-tester
  replicas: 1
  template:
    metadata:
      labels:
        app: alert-tester
    spec:
      containers:
        - name: alert-tester
          image: localhost:5000/monitoring-alert-tester
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
              cpu: "50m"
